### ISSUE TITLE
Error at 31% "A java.lang.IllegalArgumentException exception has occurred"

### ISSUE THREAD

**Issue by BigB84** [mantlik/osm2garmin#143]
Hi, thank you for this great project! However I need help.

I'm on windows 8.1 (12gb ram)

I Installed application, and stared downloading map, then I realised I don't need whole planet and I don't have 150gb free on my disk. I stopped it and reinstalled app using revo uninstaller. After this I chose whole Europe and started download. Planet file downloaded successfully then Unexpected Exception occurred:

java.lang.IllegalArgumentException: cannot add to layout: constraints must be a GridBagConstraint
	at java.awt.GridBagLayout.addLayoutComponent(Unknown Source)
	at java.awt.Container.addImpl(Unknown Source)
	at javax.swing.JToolBar.addImpl(Unknown Source)
	at java.awt.Container.add(Unknown Source)
	at javax.swing.plaf.basic.BasicToolBarUI.setFloating(Unknown Source)
	at javax.swing.plaf.basic.BasicToolBarUI.floatAt(Unknown Source)
	at javax.swing.plaf.basic.BasicToolBarUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by mantlik** [comment]
Hi, this program works with the whole planet only. Attempts to use extracts will always fail.
In addition, because the planet file has grown significantly since the program was released, you will need much more disk space than 150 gb. To be on the safe side, 400 gb would be reasonable amount.
